# -*- coding: utf-8 -*-
"""map_matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182ahaQgF1q_SeZa27DoFbega732zWjCJ

HMM-Based Map Matching Framework
=================================

This framework implements the HMM-based map matching algorithm described in:

    Newson, P., & Krumm, J. (2009). Hidden Markov Map Matching Through Noise
    and Sparseness. In Proceedings of the 17th ACM SIGSPATIAL International
    Conference on Advances in Geographic Information Systems.

Map matching is the problem of matching a sequence of noisy GPS observations
to the correct road segments in a road network. The HMM approach models:

  - Hidden states:   Candidate road segments for each GPS observation
  - Observations:    GPS latitude/longitude measurements
  - Emission prob:   How likely a GPS point is, given a candidate road segment
                     (based on distance from GPS point to road segment)
  - Transition prob: How likely a transition between two road segments is
                     (based on whether the route distance matches the GPS
                     straight-line distance)
  - Viterbi alg:     Finds the most likely sequence of road segments

Students: You must implement the four functions marked with TODO.
All helper functions are already provided.

Usage:
    python map_matching_framework.py

Dependencies:
    pip install osmnx networkx scipy shapely folium numpy pandas geopandas
'''
"""

# pip install osmnx networkx scipy shapely folium numpy pandas geopandas

import os
import glob
import math
import warnings
from typing import List, Tuple, Dict, Optional, NamedTuple
import osmnx as ox
import numpy as np
import pandas as pd
import geopandas as gpd
import networkx as nx
from scipy.spatial import KDTree
from shapely.geometry import LineString, Point
from shapely.ops import nearest_points
import folium

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

class GPSPoint(NamedTuple):
    """A single GPS observation."""
    lat: float
    lon: float
    flag: int        # 1 = occupied (taxi has passenger), 0 = free
    timestamp: int   # Unix timestamp


class Candidate(NamedTuple):
    """A candidate road segment for a GPS observation."""
    edge_id: Tuple[int, int, int]   # (u, v, key) identifying the edge
    proj_point: Tuple[float, float] # (lat, lon) of nearest point on the edge
    distance: float                  # great-circle distance in meters from GPS to proj_point

"""# ---------------------------------------------------------------------------
# PROVIDED helper functions (already implemented)
# ---------------------------------------------------------------------------
"""

def load_road_network(
    graphml_path: str = "sf_road_network.graphml",
) -> Tuple[nx.MultiDiGraph, gpd.GeoDataFrame, KDTree, np.ndarray]:
    """
    Load the road network and build a spatial index for fast candidate search.

    Parameters
    ----------
    graphml_path : str
        Path to the GraphML file exported by osmnx.

    Returns
    -------
    G : nx.MultiDiGraph
        The road network graph.
    edges_gdf : gpd.GeoDataFrame
        GeoDataFrame of edges with geometry (in EPSG:4326, i.e., lon/lat).
    kdtree : scipy.spatial.KDTree
        KDTree built from edge midpoints (in lon/lat radians for haversine).
    edge_index : np.ndarray
        Array of (u, v, key) tuples aligned with the KDTree points, so
        kdtree result index i corresponds to edge edge_index[i].
    """
    print(f"Loading road network from {graphml_path}...")
    G = ox.load_graphml(graphml_path)

    # Convert graph to GeoDataFrames (osmnx 2.x API)
    nodes_gdf, edges_gdf = ox.graph_to_gdfs(G)
    edges_gdf = edges_gdf.reset_index()  # makes u, v, key regular columns

    print(f"  Nodes: {len(nodes_gdf)},  Edges: {len(edges_gdf)}")

    # Build a KDTree from edge midpoints for fast spatial queries.
    # We sample points along each edge geometry so that long edges are
    # represented by multiple points.  This gives much better nearest-
    # neighbor results than using only the midpoint.
    sample_coords = []   # (lat_rad, lon_rad)
    sample_edge_idx = [] # index into edges_gdf

    for idx, row in edges_gdf.iterrows():
        geom = row["geometry"]
        # Sample every ~50 m along the edge
        length_deg = geom.length  # approximate degrees
        n_samples = max(2, int(length_deg / 0.0005) + 1)
        for frac in np.linspace(0, 1, n_samples):
            pt = geom.interpolate(frac, normalized=True)
            sample_coords.append((math.radians(pt.y), math.radians(pt.x)))
            sample_edge_idx.append(idx)

    sample_coords = np.array(sample_coords)
    sample_edge_idx = np.array(sample_edge_idx)

    # KDTree on (lat_rad, lon_rad) -- we use Euclidean distance on radians
    # as an approximation; actual filtering uses haversine.
    kdtree = KDTree(sample_coords)

    # Build edge_index: maps sample index -> (u, v, key)
    edge_index = np.array(
        list(
            zip(
                edges_gdf.loc[sample_edge_idx, "u"].values,
                edges_gdf.loc[sample_edge_idx, "v"].values,
                edges_gdf.loc[sample_edge_idx, "key"].values,
            )
        )
    )

    print("  Spatial index built.")
    return G, edges_gdf, kdtree, edge_index


def load_trajectory(filepath: str) -> List[GPSPoint]:
    """
    Read a trajectory file.

    Expected format (space-separated, one point per line):
        lat lon flag timestamp

    Parameters
    ----------
    filepath : str
        Path to the trajectory text file.

    Returns
    -------
    trajectory : list of GPSPoint
        The GPS observations in chronological order.
    """
    points = []
    with open(filepath, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 4:
                continue
            lat, lon = float(parts[0]), float(parts[1])
            flag = int(parts[2])
            ts = int(parts[3])
            points.append(GPSPoint(lat, lon, flag, ts))
    # Sort by timestamp
    points.sort(key=lambda p: p.timestamp)
    return points


def great_circle_distance(lat1: float, lon1: float,
                          lat2: float, lon2: float) -> float:
    """
    Compute the great-circle (haversine) distance between two points
    given in decimal degrees.

    Parameters
    ----------
    lat1, lon1 : float
        Latitude and longitude of point 1 (degrees).
    lat2, lon2 : float
        Latitude and longitude of point 2 (degrees).

    Returns
    -------
    distance : float
        Distance in meters.
    """
    R = 6_371_000  # Earth radius in meters
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = (math.sin(dphi / 2) ** 2
         + math.cos(phi1) * math.cos(phi2) * math.sin(dlam / 2) ** 2)
    return 2 * R * math.asin(math.sqrt(a))


def _project_point_on_line(
    lat: float, lon: float, geom: LineString
) -> Tuple[float, float, float]:
    """
    Project a GPS point onto a LineString (road segment geometry) and
    return the projected point and great-circle distance.

    Parameters
    ----------
    lat, lon : float
        GPS point in degrees.
    geom : shapely.geometry.LineString
        The road segment geometry (coordinates are lon, lat).

    Returns
    -------
    proj_lat, proj_lon : float
        Coordinates of the nearest point on the segment (degrees).
    dist : float
        Great-circle distance in meters from (lat, lon) to the projection.
    """
    gps_pt = Point(lon, lat)  # shapely uses (x, y) = (lon, lat)
    proj_pt = nearest_points(geom, gps_pt)[0]
    proj_lat, proj_lon = proj_pt.y, proj_pt.x
    dist = great_circle_distance(lat, lon, proj_lat, proj_lon)
    return proj_lat, proj_lon, dist


def get_candidates(
    lat: float,
    lon: float,
    edges_gdf: gpd.GeoDataFrame,
    kdtree: KDTree,
    edge_index: np.ndarray,
    radius: float = 200.0,
) -> List[Candidate]:
    """
    Find candidate road segments within `radius` meters of a GPS point.

    Uses the KDTree for a fast initial filter, then refines with exact
    projection onto each candidate edge geometry.

    Parameters
    ----------
    lat, lon : float
        GPS observation in decimal degrees.
    edges_gdf : gpd.GeoDataFrame
        Edge GeoDataFrame from load_road_network().
    kdtree : scipy.spatial.KDTree
        Spatial index from load_road_network().
    edge_index : np.ndarray
        Edge lookup array from load_road_network().
    radius : float
        Search radius in meters (default 200 m, per the paper).

    Returns
    -------
    candidates : list of Candidate
        Each candidate has (edge_id, proj_point, distance).
        Sorted by distance ascending. Duplicates by edge_id are removed
        (keeping the closest projection).
    """
    # Convert radius to approximate radians for KDTree query
    radius_rad = radius / 6_371_000  # Earth radius in meters

    # Query KDTree
    lat_rad = math.radians(lat)
    lon_rad = math.radians(lon)
    idxs = kdtree.query_ball_point([lat_rad, lon_rad], radius_rad)

    if not idxs:
        return []

    # Deduplicate edges
    seen_edges = set()
    candidate_edge_indices = []  # row indices into edges_gdf
    candidate_edge_ids = []      # (u, v, key) tuples
    for i in idxs:
        u, v, key = int(edge_index[i][0]), int(edge_index[i][1]), int(edge_index[i][2])
        eid = (u, v, key)
        if eid not in seen_edges:
            seen_edges.add(eid)
            # Find the row in edges_gdf for this edge
            candidate_edge_ids.append(eid)

    # Project GPS point onto each candidate edge for exact distance
    candidates = []
    for eid in candidate_edge_ids:
        u, v, key = eid
        row = edges_gdf[
            (edges_gdf["u"] == u)
            & (edges_gdf["v"] == v)
            & (edges_gdf["key"] == key)
        ]
        if row.empty:
            continue
        geom = row.iloc[0]["geometry"]
        proj_lat, proj_lon, dist = _project_point_on_line(lat, lon, geom)
        if dist <= radius:
            candidates.append(Candidate(eid, (proj_lat, proj_lon), dist))

    # Sort by distance
    candidates.sort(key=lambda c: c.distance)
    return candidates


def shortest_path_distance(
    G: nx.MultiDiGraph, u: int, v: int
) -> float:
    """
    Compute the shortest path distance (in meters) between nodes u and v
    in the road network using Dijkstra's algorithm.

    Parameters
    ----------
    G : nx.MultiDiGraph
        The road network graph. Edges should have a 'length' attribute
        (in meters), which osmnx adds automatically.
    u, v : int
        Source and target node IDs.

    Returns
    -------
    distance : float
        Shortest path distance in meters.  Returns float('inf') if no
        path exists.
    """
    try:
        return nx.shortest_path_length(G, u, v, weight="length")
    except (nx.NetworkXNoPath, nx.NodeNotFound):
        return float("inf")


def preprocess_trajectory(
    trajectory: List[GPSPoint], sigma_z: float = 4.07
) -> List[GPSPoint]:
    """
    Remove GPS points that are within 2 * sigma_z meters of the previous
    retained point. This is the preprocessing step described in the paper
    to handle stationary noise.

    Parameters
    ----------
    trajectory : list of GPSPoint
        Raw GPS observations sorted by timestamp.
    sigma_z : float
        GPS noise standard deviation in meters.

    Returns
    -------
    filtered : list of GPSPoint
        Filtered trajectory.
    """
    if not trajectory:
        return []
    threshold = 2.0 * sigma_z
    filtered = [trajectory[0]]
    for pt in trajectory[1:]:
        prev = filtered[-1]
        dist = great_circle_distance(prev.lat, prev.lon, pt.lat, pt.lon)
        if dist > threshold:
            filtered.append(pt)
    return filtered


def _get_nearest_node(G: nx.MultiDiGraph, lat: float, lon: float) -> int:
    """Return the nearest graph node to a (lat, lon) point."""
    return ox.nearest_nodes(G, lon, lat)  # osmnx takes (X=lon, Y=lat)


def visualize_matching(
    trajectory: List[GPSPoint],
    matched: List[Tuple[Tuple[int, int, int], Tuple[float, float]]],
    edges_gdf: gpd.GeoDataFrame,
    output_path: str = "map_matching_result.html",
) -> folium.Map:
    """
    Visualize the map matching result on an interactive Folium map.

    Draws:
      - Red circles: raw GPS observations
      - Blue circles: matched (projected) points on road segments
      - Blue polyline: connecting the matched points
      - Green highlighted road segments: the matched edges

    Parameters
    ----------
    trajectory : list of GPSPoint
        Original GPS observations.
    matched : list of (edge_id, (proj_lat, proj_lon))
        Output of the Viterbi algorithm — one matched edge per GPS point.
    edges_gdf : gpd.GeoDataFrame
        Edge GeoDataFrame for drawing matched road segments.
    output_path : str
        Where to save the HTML file.

    Returns
    -------
    m : folium.Map
    """
    center_lat = np.mean([p.lat for p in trajectory])
    center_lon = np.mean([p.lon for p in trajectory])
    m = folium.Map(location=[center_lat, center_lon], zoom_start=15)

    # Raw GPS trace (red)
    for pt in trajectory:
        folium.CircleMarker(
            location=[pt.lat, pt.lon],
            radius=4,
            color="red",
            fill=True,
            fill_opacity=0.7,
            popup=f"GPS ({pt.lat:.5f}, {pt.lon:.5f})",
        ).add_to(m)

    # GPS trace line (red, dashed)
    gps_coords = [[p.lat, p.lon] for p in trajectory]
    folium.PolyLine(gps_coords, color="red", weight=2, dash_array="5").add_to(m)

    # Matched points (blue)
    matched_coords = []
    for edge_id, (plat, plon) in matched:
        matched_coords.append([plat, plon])
        folium.CircleMarker(
            location=[plat, plon],
            radius=4,
            color="blue",
            fill=True,
            fill_opacity=0.7,
            popup=f"Matched ({plat:.5f}, {plon:.5f})\nEdge: {edge_id}",
        ).add_to(m)

    # Matched trace line (blue)
    if matched_coords:
        folium.PolyLine(matched_coords, color="blue", weight=3).add_to(m)

    # Highlight matched road segments (green)
    matched_edge_ids = set(edge_id for edge_id, _ in matched)
    for eid in matched_edge_ids:
        u, v, key = eid
        row = edges_gdf[
            (edges_gdf["u"] == u)
            & (edges_gdf["v"] == v)
            & (edges_gdf["key"] == key)
        ]
        if not row.empty:
            geom = row.iloc[0]["geometry"]
            coords = [(lat, lon) for lon, lat in geom.coords]
            folium.PolyLine(coords, color="green", weight=5, opacity=0.6).add_to(m)

    # Add legend
    legend_html = """
    <div style="position: fixed; bottom: 30px; left: 30px; z-index: 1000;
                background: white; padding: 10px; border-radius: 5px;
                border: 2px solid grey; font-size: 14px;">
        <b>Legend</b><br>
        <span style="color:red;">&#9679;</span> GPS observations<br>
        <span style="color:blue;">&#9679;</span> Matched points<br>
        <span style="color:green;">&#9644;</span> Matched road segments
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend_html))

    m.save(output_path)
    print(f"Map saved to {output_path}")
    return m

"""# TODO: Functions for you to implement"""

def emission_probability(distance: float, sigma_z: float = 4.07) -> float:
    """
    Compute the emission probability of a GPS observation given a candidate
    road segment.

    This implements Equation (1) from Newson & Krumm (2009):

        p(z_t | r_i) = (1 / (sqrt(2 * pi) * sigma_z))
                        * exp(-0.5 * (distance / sigma_z)^2)

    where `distance` is the great-circle distance (in meters) between the
    GPS observation z_t and the nearest point x_{t,i} on road segment r_i.

    The emission probability models how likely it is to observe a GPS reading
    at a certain distance from a road segment, assuming Gaussian noise.

    Parameters
    ----------
    distance : float
        Great-circle distance in meters between the GPS observation and the
        nearest point on the candidate road segment (||z_t - x_{t,i}||).
    sigma_z : float
        Standard deviation of GPS noise in meters.
        Default is 4.07 m (the median value from the paper for clean GPS).

    Returns
    -------
    prob : float
        The emission probability (a value between 0 and 1/denominator).

    Example
    -------
    >>> emission_probability(0.0, sigma_z=4.07)   # point exactly on road
    0.0979...
    >>> emission_probability(10.0, sigma_z=4.07)   # 10 m away from road
    0.0176...
    """
    # Calculate scaling constant
    c = 1.0 / (math.sqrt(2.0 * math.pi) * sigma_z)

    # Calculate exponential decay
    decay = math.exp(-0.5 * (distance / sigma_z) ** 2)

    return c * decay

def transition_probability(d_t: float, beta: float = 3.0) -> float:
    """
    Compute the transition probability between two consecutive candidate
    road segments.

    This implements Equation (2) from Newson & Krumm (2009):

        p(d_t) = (1 / beta) * exp(-d_t / beta)

    where d_t is defined in Equation (3):

        d_t = | great_circle_distance(z_t, z_{t+1})
              - route_distance(x_{t,i}, x_{t+1,j}) |

    The transition probability captures the intuition that, for a correct
    match, the shortest-path route distance between matched points should
    be similar to the straight-line distance between GPS observations.
    When d_t is small (route ≈ straight line), the probability is high.

    Parameters
    ----------
    d_t : float
        The absolute difference (in meters) between the great-circle
        distance of two consecutive GPS points and the shortest-path
        route distance between the corresponding matched road points.
        See Equation (3) in the paper.
    beta : float
        The parameter of the exponential distribution (in meters).
        Default is 3.0 m. Can be estimated from training data as the
        mean of d_t values across the dataset.

    Returns
    -------
    prob : float
        The transition probability.

    Example
    -------
    >>> transition_probability(0.0, beta=3.0)   # perfect match
    0.3333...
    >>> transition_probability(10.0, beta=3.0)  # 10 m discrepancy
    0.01195...
    """
    return (1.0 / beta) * math.exp(-d_t / beta)

def viterbi(
    candidates_per_step: List[List[Candidate]],
    emission_probs: List[List[float]],
    transition_probs: List[List[List[float]]],
) -> List[Tuple[Tuple[int, int, int], Tuple[float, float]]]:
    """
    Run the Viterbi algorithm on the HMM lattice to find the most likely
    sequence of road segments.

    The HMM lattice has:
      - T time steps (one per GPS observation)
      - At each time step t, N_t candidate road segments
      - Emission probabilities: how likely each candidate is given the GPS obs
      - Transition probabilities: how likely each pair of consecutive
        candidates is (from step t to step t+1)

    The Viterbi algorithm finds the sequence of candidates (one per time
    step) that maximizes the product of emission and transition probabilities.

    IMPORTANT: Use log-probabilities to avoid numerical underflow!
        log(product of probs) = sum of log(probs)
    Handle zero probabilities by using a very small value (e.g., 1e-50)
    before taking the log.

    Algorithm outline (dynamic programming):
    -----------------------------------------
    1. Initialization (t = 0):
       For each candidate i at step 0:
           V[0][i] = log(emission_probs[0][i])
           parent[0][i] = None

    2. Recursion (t = 1, 2, ..., T-1):
       For each candidate j at step t:
           V[t][j] = max over all candidates i at step t-1 of:
               V[t-1][i] + log(transition_probs[t-1][i][j]) + log(emission_probs[t][j])
           parent[t][j] = argmax i of the above

    3. Termination:
       best_last = argmax j of V[T-1][j]

    4. Backtracking:
       Follow parent pointers from best_last back to step 0 to recover
       the best sequence.

    Parameters
    ----------
    candidates_per_step : list of list of Candidate
        candidates_per_step[t] is the list of Candidate objects at time t.
        Length T (number of time steps).
    emission_probs : list of list of float
        emission_probs[t][i] is the emission probability for candidate i
        at time step t.
    transition_probs : list of list of list of float
        transition_probs[t][i][j] is the transition probability from
        candidate i at step t to candidate j at step t+1.
        Length T-1.

    Returns
    -------
    best_path : list of (edge_id, (proj_lat, proj_lon))
        The most likely sequence of matched road segments, one per time
        step.  Each element is a tuple of the edge ID and the projected
        point coordinates.

    Notes
    -----
    - If a time step has no candidates, you may skip it or handle it
      gracefully (e.g., break the sequence).
    - The paper discusses handling breaks in the path; for simplicity,
      you can assume all time steps have at least one candidate.
    """
    T = len(candidates_per_step)
    if T == 0:
        return []

    TINY = 1e-50  # prevents log(0)
    V = []        # best log-prob ending at each candidate at each time step
    parent = []   # tracks which predecessor led to each candidate

    # Initialization: t=0
    n0 = len(candidates_per_step[0])
    V.append([math.log(max(emission_probs[0][i], TINY)) for i in range(n0)]) # Just the emission probability
    parent.append([None] * n0)

    # Forward pass: t=1 to T-1
    # For each candidate j, find the best predecessor i from t-1
    for t in range(1, T):
        n_curr = len(candidates_per_step[t])
        n_prev = len(candidates_per_step[t - 1])
        v_t = []
        p_t = []
        for j in range(n_curr):
            best_score = -math.inf
            best_i = 0
            for i in range(n_prev):
                # best score at i + transition i→j
                score = V[t - 1][i] + math.log(max(transition_probs[t - 1][i][j], TINY))
                if score > best_score:
                    best_score = score
                    best_i = i  # remember which i won
            # winning score + emission prob of j at time t
            v_t.append(best_score + math.log(max(emission_probs[t][j], TINY)))
            p_t.append(best_i)
        # save completed row before moving to next time step
        V.append(v_t)
        parent.append(p_t)

    # Backtracking
    # Start from the best final candidate and follow parent pointers backwards
    path = [None] * T
    path[T - 1] = max(range(len(V[T - 1])), key=lambda j: V[T - 1][j])
    for t in range(T - 2, -1, -1):  # counts down from T-2 to 0
        path[t] = parent[t + 1][path[t + 1]]

    # Build output
    # Convert path indices to (edge_id, proj_point) tuples
    result = []
    for t in range(T):
        candidate = candidates_per_step[t][path[t]]
        result.append((candidate.edge_id, candidate.proj_point))

    return result

def hmm_map_match(
    trajectory: List[GPSPoint],
    G: nx.MultiDiGraph,
    edges_gdf: gpd.GeoDataFrame,
    kdtree: KDTree,
    edge_index: np.ndarray,
    sigma_z: float = 4.07,
    beta: float = 3.0,
) -> List[Tuple[Tuple[int, int, int], Tuple[float, float]]]:
    """
    Perform HMM-based map matching on a GPS trajectory.

    This is the main orchestrator function that:
    1. Preprocesses the trajectory (removes near-stationary points)
    2. For each GPS point, finds candidate road segments
    3. Computes emission probabilities for each candidate
    4. Computes transition probabilities between consecutive candidates
    5. Runs the Viterbi algorithm to find the best path

    Parameters
    ----------
    trajectory : list of GPSPoint
        GPS observations sorted by timestamp.
    G : nx.MultiDiGraph
        Road network graph.
    edges_gdf : gpd.GeoDataFrame
        Edge GeoDataFrame with geometry.
    kdtree : scipy.spatial.KDTree
        Spatial index of road edges.
    edge_index : np.ndarray
        Edge lookup array aligned with KDTree.
    sigma_z : float
        GPS noise standard deviation in meters (default 4.07).
    beta : float
        Exponential distribution parameter for transitions (default 3.0).

    Returns
    -------
    matched : list of (edge_id, (proj_lat, proj_lon))
        One matched road segment per (preprocessed) GPS observation.
    """
    # Step 1: Preprocess — remove near-duplicate points
    trajectory = preprocess_trajectory(trajectory, sigma_z)
    print(f"  After preprocessing: {len(trajectory)} GPS points")

    if len(trajectory) < 2:
        print("  Too few points after preprocessing.")
        return []

    # Step 2: Find candidate road segments for each GPS point
    print("  Finding candidate road segments...")
    candidates_per_step: List[List[Candidate]] = []
    valid_steps = []  # indices of steps that have at least one candidate

    for t, pt in enumerate(trajectory):
        cands = get_candidates(pt.lat, pt.lon, edges_gdf, kdtree, edge_index,
                               radius=200.0)
        if cands:
            candidates_per_step.append(cands)
            valid_steps.append(t)
        else:
            # No candidates found — skip this point
            # (In a production system, you'd handle path breaks here)
            candidates_per_step.append([])

    # Filter to only steps with candidates
    filtered_trajectory = [trajectory[t] for t in valid_steps]
    filtered_candidates = [candidates_per_step[t] for t in valid_steps]

    if len(filtered_candidates) < 2:
        print("  Too few points with candidates.")
        return []

    T = len(filtered_candidates)
    print(f"  {T} steps with candidates")

    # =====================================================================
    # Step 3: Compute emission probabilities
    # =====================================================================
    # For each time step t and each candidate i, compute:
    #     emission_probs[t][i] = emission_probability(candidate.distance, sigma_z)
    # =====================================================================
    emission_probs: List[List[float]] = []
    for t in range(T):
        step_probs = []
        for cand in filtered_candidates[t]:
            prob = emission_probability(cand.distance, sigma_z)
            step_probs.append(prob)
        emission_probs.append(step_probs)

    # =====================================================================
    # Step 4: Compute transition probabilities
    # =====================================================================
    # For each pair of consecutive time steps (t, t+1) and each pair of
    # candidates (i at step t, j at step t+1), compute:
    #
    #   gc_dist = great_circle_distance(z_t, z_{t+1})  -- GPS straight line
    #   route_dist = shortest_path_distance(G, u_i, v_j) -- road network
    #   d_t = |gc_dist - route_dist|
    #   transition_probs[t][i][j] = transition_probability(d_t, beta)
    #
    # For route_dist, we need the nearest nodes to the projected points.
    # We use the endpoints of the matched edge as approximation:
    #   - For candidate i at step t:   node = edge_id[1] (the 'v' node)
    #   - For candidate j at step t+1: node = edge_id[0] (the 'u' node)
    # =====================================================================
    print("  Computing transition probabilities (this may take a moment)...")
    transition_probs: List[List[List[float]]] = []

    for t in range(T - 1):
        pt_curr = filtered_trajectory[t]
        pt_next = filtered_trajectory[t + 1]

        # Great-circle distance between consecutive GPS points
        gc_dist = great_circle_distance(
            pt_curr.lat, pt_curr.lon, pt_next.lat, pt_next.lon
        )

        trans_matrix: List[List[float]] = []
        for i, cand_i in enumerate(filtered_candidates[t]):
            row: List[float] = []
            # Use the downstream node of candidate i's edge
            node_i = cand_i.edge_id[1]  # 'v' node

            for j, cand_j in enumerate(filtered_candidates[t + 1]):
                # Use the upstream node of candidate j's edge
                node_j = cand_j.edge_id[0]  # 'u' node

                # Shortest path distance along the road network
                if node_i == node_j:
                    route_dist = 0.0
                else:
                    route_dist = shortest_path_distance(G, node_i, node_j)

                # d_t = |great_circle_dist - route_dist|  (Equation 3)
                d_t = abs(gc_dist - route_dist)

                prob = transition_probability(d_t, beta)
                row.append(prob)
            trans_matrix.append(row)
        transition_probs.append(trans_matrix)

    # =====================================================================
    # Step 5: Run the Viterbi algorithm
    # =====================================================================
    print("  Running Viterbi algorithm...")
    matched = viterbi(filtered_candidates, emission_probs, transition_probs)

    print(f"  Matched {len(matched)} points to road segments.")
    return matched

def main():
    """
    Main entry point: load data, run map matching, visualize results.
    """
    # Configuration - Updated with Drive paths
    GRAPHML_PATH = "/content/drive/MyDrive/aiforcps/hw1/sf_road_network.graphml"
    TRAJ_DIR = "/content/drive/MyDrive/aiforcps/hw1/Trajectories"
    OUTPUT_HTML = "map_matching_result.html"

    # ------------------------------------------------------------------
    # 1. Load road network
    # ------------------------------------------------------------------
    G, edges_gdf, kdtree, edge_index = load_road_network(GRAPHML_PATH)

    # ------------------------------------------------------------------
    # 2. Pick an example trajectory
    # ------------------------------------------------------------------
    traj_files = sorted(glob.glob(os.path.join(TRAJ_DIR, "*.txt")))
    if not traj_files:
        print(f"No trajectory files found in {TRAJ_DIR}/")
        return

    # Use the first trajectory file as an example
    traj_file = traj_files[0]
    print(f"\nLoading trajectory: {traj_file}")
    trajectory = load_trajectory(traj_file)
    print(f"  {len(trajectory)} GPS points loaded")

    # Limit to a reasonable number of points for demonstration
    MAX_POINTS = 50
    if len(trajectory) > MAX_POINTS:
        print(f"  Using first {MAX_POINTS} points for demonstration")
        trajectory = trajectory[:MAX_POINTS]

    # ------------------------------------------------------------------
    # 3. Run HMM map matching
    # ------------------------------------------------------------------
    print("\nRunning HMM map matching...")
    matched = hmm_map_match(
        trajectory, G, edges_gdf, kdtree, edge_index,
        sigma_z=4.07, beta=3.0,
    )

    if not matched:
        print("Map matching produced no results.")
        return

    # ------------------------------------------------------------------
    # 4. Visualize
    # ------------------------------------------------------------------
    print(f"\nVisualizing results...")
    visualize_matching(trajectory, matched, edges_gdf, OUTPUT_HTML)
    print("Done!")

# Colab-only: drive mounting removed for local execution

if __name__ == "__main__":
    main()